### ISSUE TITLE
Question: is the normal behavior that when I start the app there is not css

### ISSUE THREAD

**Issue by israteneda** [lorey/personal-crm#21]
Great app! thanks for sharing

I was trying the app and the welcome page doesn't have CSS that is normal, or I'm missing some config

![image](https://user-images.githubusercontent.com/20668624/124343447-24425580-db91-11eb-834c-5243707c50fe.png)

**Comment by lorey** [comment]
Hi @israteneda, For Django, you need to run a command called collectstatic. I should add it to the docker setup.

So to have the CSS in place, you run `docker-compose exec web ./manage.py collectstatic`

**Comment by israteneda** [comment]
Thanks for your answer @lorey but when I run the command, I get this error:
```
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```

**Comment by lorey** [comment]
Sorry, my mistake. The index page is actually without a stylesheet. The app itself (at /app/) has a proper stylesheet.
